### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by TheDiamondYT1** [ljyloo/LittleBrother#8]
Does this plugin work at the current state? I can help continue development.

**Comment by alejzeis** [comment]
No it doesn't, there is no networking yet.

On Thursday, September 10, 2015, RandomAltThingy notifications@github.com
wrote:

> Does this plugin work at the current state? I can help continue
> development.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ljyloo/LittleBrother/issues/8.

##

**Comment by TheDiamondYT1** [comment]
@jython234 It has alot of the packets, but I'm assuming it doesn't send them :P

**Comment by alejzeis** [comment]
It doesn't recieve them either. And the protocol is outdated (20) current
is 34

On Thursday, September 10, 2015, RandomAltThingy notifications@github.com
wrote:

> @jython234 https://github.com/jython234 It has alot of the packets, but
> I'm assuming it doesn't send them :P
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ljyloo/LittleBrother/issues/8#issuecomment-139224025.

##

**Comment by TheDiamondYT1** [comment]
@jython234 I see. What happened to RedstoneTorch proxy that you were making?

**Comment by alejzeis** [comment]
@RandomAltThingy No time, I am overloaded with school.

On Thursday, September 10, 2015, RandomAltThingy notifications@github.com
wrote:

> @jython234 https://github.com/jython234 I see. What happened to
> RedstoneTorch proxy that you were making?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ljyloo/LittleBrother/issues/8#issuecomment-139224997.

##

**Comment by TheDiamondYT1** [comment]
@jython234 So am I but I find the time to do many things.
